### ISSUE TITLE
Unstable on Asterisk

### ISSUE THREAD

**Issue by azharkhn** [tic-ull/func_redis#1]
I have checked this module on both asterisk 1.8 and 11.8 and found very unusual behavior i.e. it disconnected connection from asterisk-cli and asterisk restarted. :( and redis command on asterisk-cli became unavailable where I re-loaded this module but didn't work for me.

**Comment by lumasepa** [comment]
At the moment this module isn't ready for production because it have some problems with threading, because the hiredis lib is not thread safe, at the moment I don't have time to fix it, but as soon as I can I'm going to change the hiredis lib for another one that can have thread safety.

**Comment by azharkhn** [comment]
Thanks :)
anxiously waiting for the change.
